version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: mariadb              
      MYSQL_USER: admin               
      MYSQL_PASSWORD: admin         
    ports:
      - "3306:3306"